[package]
name = "hash_analyzer_crack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
md5 = "0.7.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
